// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

// GetAPIKeyResponseBody - Success
type GetAPIKeyResponseBody struct {
	Success bool `json:"success"`
	// The name of the team the API key belongs to.
	TeamName string `json:"teamName"`
}

func (o *GetAPIKeyResponseBody) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *GetAPIKeyResponseBody) GetTeamName() string {
	if o == nil {
		return ""
	}
	return o.TeamName
}

type GetAPIKeyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *GetAPIKeyResponseBody
}

func (o *GetAPIKeyResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAPIKeyResponse) GetObject() *GetAPIKeyResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
