// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

type GetContactsCustomFieldsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful.
	CustomFields []components.CustomField
}

func (o *GetContactsCustomFieldsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetContactsCustomFieldsResponse) GetCustomFields() []components.CustomField {
	if o == nil {
		return nil
	}
	return o.CustomFields
}
