// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

type GetListsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful.
	MailingLists []components.MailingList
}

func (o *GetListsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetListsResponse) GetMailingLists() []components.MailingList {
	if o == nil {
		return nil
	}
	return o.MailingLists
}
