// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

type PostContactsCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful create.
	ContactSuccessResponse *components.ContactSuccessResponse
}

func (o *PostContactsCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostContactsCreateResponse) GetContactSuccessResponse() *components.ContactSuccessResponse {
	if o == nil {
		return nil
	}
	return o.ContactSuccessResponse
}
