// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

type PostTransactionalResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful send.
	TransactionalSuccessResponse *components.TransactionalSuccessResponse
}

func (o *PostTransactionalResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostTransactionalResponse) GetTransactionalSuccessResponse() *components.TransactionalSuccessResponse {
	if o == nil {
		return nil
	}
	return o.TransactionalSuccessResponse
}
