// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/loops-go/models/components"
)

type PutContactsUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful update.
	ContactSuccessResponse *components.ContactSuccessResponse
}

func (o *PutContactsUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PutContactsUpdateResponse) GetContactSuccessResponse() *components.ContactSuccessResponse {
	if o == nil {
		return nil
	}
	return o.ContactSuccessResponse
}
