// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// ContactFailureResponse - Bad request (e.g. `email` or `userId` are missing).
type ContactFailureResponse struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

var _ error = &ContactFailureResponse{}

func (e *ContactFailureResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
