// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// ContactFailureResponse - Bad request (e.g. `email` or `userId` are missing).
type ContactFailureResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

var _ error = &ContactFailureResponse{}

func (e *ContactFailureResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
