// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type EventFailureResponse struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

var _ error = &EventFailureResponse{}

func (e *EventFailureResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
