// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type EventFailureResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

var _ error = &EventFailureResponse{}

func (e *EventFailureResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
