// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/loops-go/models/components"
)

// GetAPIKeyResponseBody - Invalid API key
type GetAPIKeyResponseBody struct {
	Error_   *string                 `json:"error,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &GetAPIKeyResponseBody{}

func (e *GetAPIKeyResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
