// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/speakeasy-sdks/loops-go/models/components"
)

// PostContactsDeleteResponseBody - Internal error.
type PostContactsDeleteResponseBody struct {
	Success  *bool                   `json:"success,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostContactsDeleteResponseBody{}

func (e *PostContactsDeleteResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
