// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type Error struct {
	Path    *string `json:"path,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *Error) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *Error) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

type TransactionalFailure2Response struct {
	Success *bool  `json:"success,omitempty"`
	Error_  *Error `json:"error,omitempty"`
}

var _ error = &TransactionalFailure2Response{}

func (e *TransactionalFailure2Response) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
