// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ContactDeleteRequest struct {
	Email  string `json:"email"`
	UserID string `json:"userId"`
}

func (o *ContactDeleteRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *ContactDeleteRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}
