// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ContactSuccessResponse struct {
	Success *bool   `json:"success,omitempty"`
	ID      *string `json:"id,omitempty"`
}

func (o *ContactSuccessResponse) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *ContactSuccessResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}
