// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// MailingLists - An object of mailing list IDs and boolean subscription statuses.
type MailingLists struct {
}

type ContactRequest struct {
	Email      string  `json:"email"`
	FirstName  *string `json:"firstName,omitempty"`
	LastName   *string `json:"lastName,omitempty"`
	Subscribed *bool   `json:"subscribed,omitempty"`
	UserGroup  *string `json:"userGroup,omitempty"`
	UserID     *string `json:"userId,omitempty"`
	// An object of mailing list IDs and boolean subscription statuses.
	MailingLists *MailingLists `json:"mailingLists,omitempty"`
}

func (o *ContactRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *ContactRequest) GetFirstName() *string {
	if o == nil {
		return nil
	}
	return o.FirstName
}

func (o *ContactRequest) GetLastName() *string {
	if o == nil {
		return nil
	}
	return o.LastName
}

func (o *ContactRequest) GetSubscribed() *bool {
	if o == nil {
		return nil
	}
	return o.Subscribed
}

func (o *ContactRequest) GetUserGroup() *string {
	if o == nil {
		return nil
	}
	return o.UserGroup
}

func (o *ContactRequest) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *ContactRequest) GetMailingLists() *MailingLists {
	if o == nil {
		return nil
	}
	return o.MailingLists
}
