// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ContactSuccessResponse struct {
	Success bool   `json:"success"`
	ID      string `json:"id"`
}

func (o *ContactSuccessResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *ContactSuccessResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
