// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ContactDeleteResponse struct {
	Success *bool   `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *ContactDeleteResponse) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *ContactDeleteResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
