// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type ContactDeleteRequest struct {
	Email  *string `json:"email,omitempty"`
	UserID *string `json:"userId,omitempty"`
}

func (o *ContactDeleteRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *ContactDeleteRequest) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}
