// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CustomField struct {
	Key   *string `json:"key,omitempty"`
	Label *string `json:"label,omitempty"`
	Type  *string `json:"type,omitempty"`
}

func (o *CustomField) GetKey() *string {
	if o == nil {
		return nil
	}
	return o.Key
}

func (o *CustomField) GetLabel() *string {
	if o == nil {
		return nil
	}
	return o.Label
}

func (o *CustomField) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}
