// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CustomField struct {
	Key   string `json:"key"`
	Label string `json:"label"`
	Type  string `json:"type"`
}

func (o *CustomField) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *CustomField) GetLabel() string {
	if o == nil {
		return ""
	}
	return o.Label
}

func (o *CustomField) GetType() string {
	if o == nil {
		return ""
	}
	return o.Type
}
