// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// EventRequestMailingLists - An object of mailing list IDs and boolean subscription statuses.
type EventRequestMailingLists struct {
}

type EventRequest struct {
	Email     *string `json:"email,omitempty"`
	UserID    *string `json:"userId,omitempty"`
	EventName string  `json:"eventName"`
	// An object containing event property data for the event, available in emails sent by the event.
	EventProperties map[string]any `json:"eventProperties,omitempty"`
	// An object of mailing list IDs and boolean subscription statuses.
	MailingLists *EventRequestMailingLists `json:"mailingLists,omitempty"`
}

func (o *EventRequest) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *EventRequest) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *EventRequest) GetEventName() string {
	if o == nil {
		return ""
	}
	return o.EventName
}

func (o *EventRequest) GetEventProperties() map[string]any {
	if o == nil {
		return nil
	}
	return o.EventProperties
}

func (o *EventRequest) GetMailingLists() *EventRequestMailingLists {
	if o == nil {
		return nil
	}
	return o.MailingLists
}
