// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type EventSuccessResponse struct {
	Success *bool `json:"success,omitempty"`
}

func (o *EventSuccessResponse) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}
