// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type MailingList struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (o *MailingList) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *MailingList) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
