// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type TransactionalFailureResponse struct {
	Success *bool   `json:"success,omitempty"`
	Path    *string `json:"path,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (o *TransactionalFailureResponse) GetSuccess() *bool {
	if o == nil {
		return nil
	}
	return o.Success
}

func (o *TransactionalFailureResponse) GetPath() *string {
	if o == nil {
		return nil
	}
	return o.Path
}

func (o *TransactionalFailureResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
