// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Attachments struct {
	// The name of the file, shown in email clients.
	Filename string `json:"filename"`
	// The MIME type of the file.
	ContentType string `json:"contentType"`
	// The base64-encoded content of the file.
	Data string `json:"data"`
}

func (o *Attachments) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *Attachments) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *Attachments) GetData() string {
	if o == nil {
		return ""
	}
	return o.Data
}

type TransactionalRequest struct {
	Email string `json:"email"`
	// The ID of the transactional email to send.
	TransactionalID string `json:"transactionalId"`
	// If `true`, a contact will be created in your audience using the `email` value (if a matching contact doesn't already exist).
	AddToAudience *bool `json:"addToAudience,omitempty"`
	// An object containing contact data as defined by the data variables added to the transactional email template.
	DataVariables map[string]any `json:"dataVariables,omitempty"`
	// A list containing file objects to be sent along with an email message.
	Attachments []Attachments `json:"attachments,omitempty"`
}

func (o *TransactionalRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *TransactionalRequest) GetTransactionalID() string {
	if o == nil {
		return ""
	}
	return o.TransactionalID
}

func (o *TransactionalRequest) GetAddToAudience() *bool {
	if o == nil {
		return nil
	}
	return o.AddToAudience
}

func (o *TransactionalRequest) GetDataVariables() map[string]any {
	if o == nil {
		return nil
	}
	return o.DataVariables
}

func (o *TransactionalRequest) GetAttachments() []Attachments {
	if o == nil {
		return nil
	}
	return o.Attachments
}
