// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionalSuccessResponse struct {
	Success bool `json:"success"`
}

func (o *TransactionalSuccessResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}
