// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionalFailure3Response struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (o *TransactionalFailure3Response) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *TransactionalFailure3Response) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
