// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TransactionalFailureResponse struct {
	Success bool   `json:"success"`
	Path    string `json:"path"`
	Message string `json:"message"`
}

func (o *TransactionalFailureResponse) GetSuccess() bool {
	if o == nil {
		return false
	}
	return o.Success
}

func (o *TransactionalFailureResponse) GetPath() string {
	if o == nil {
		return ""
	}
	return o.Path
}

func (o *TransactionalFailureResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
